export let BrandsMock = [
  { id: 1, name: 'Toyota' },
  { id: 2, name: 'Ford' },
  { id: 3, name: 'BMW' },
  { id: 4, name: 'SUZUKI' },
  { id: 5, name: 'Fiesta' },
  { id: 6, name: 'MG' },
  { id: 7, name: 'MINI' },
  { id: 8, name: 'PEUGEOT' },
  { id: 9, name: 'KIA' },
  { id: 10, name: 'NISSAN' },
];

export let ModelsMock = [
  { id: 1, name: 'Corolla', brandId: 1 },
  { id: 2, name: 'Camry', brandId: 1 },
  { id: 3, name: 'Focus', brandId: 2 },
  { id: 4, name: 'Fiesta', brandId: 2 },
  { id: 5, name: 'X5', brandId: 3 },
  { id: 6, name: '2008', brandId: 8 },
  { id: 7, name: '3008', brandId: 8 },
  { id: 8, name: '3008', brandId: 8 },
  { id: 9, name: '208', brandId: 8 },
];
export let SeatsMock = [{ num: '2' }, { num: '4' }, { num: '5' }, { num: '6' }];
// export let CarsMock = [
//   { "id": 1, "model": "Focus",   "brand": "Ford",    "seats": 5, "available": true,  "year": 2023, "price": 20000, "image": "/assets/images/voiture1.jfif" },
//   { "id": 2, "model": "X5",      "brand": "BMW",     "seats": 7, "available": false, "year": 2022, "price": 30000, "image": "/assets/images/voiture4.jfif" },
//   { "id": 3, "model": "2008",    "brand": "PEUGEOT", "seats": 5, "available": true,  "year": 2021, "price": 40000, "image": "/assets/images/voiture5.jfif" },
//   { "id": 4, "model": "208",     "brand": "PEUGEOT", "seats": 4, "available": true,  "year": 2021, "price": 40000, "image": "/assets/images/voiture3.jfif" },
//   { "id": 5, "model": "Fiesta",  "brand": "Ford",    "seats": 5, "available": true,  "year": 2021, "price": 90000, "image": "/assets/images/voiture2.jfif" },
//   { "id": 6, "model": "Corolla", "brand": "Toyota",  "seats": 5, "available": false, "year": 2021, "price": 40000, "image": "/assets/images/suv-tt.png" },
//   { "id": 7, "model": "3008",    "brand": "PEUGEOT", "seats": 2, "available": true,  "year": 2021, "price": 80000, "image": "/assets/images/suv-tt.png" },
//   { "id": 8, "model": "Camry",   "brand": "Toyota",  "seats": 2, "available": true,  "year": 2021, "price": 80000, "image": "/assets/images/suv-tt.png" },

// ]
// { "id": 11, "name": "JEEP" },
// { "id": 12, "name": "SUZUKI" },
// { "id": 13, "name": "HONDA" },
// { "id": 14, "name": "VOLKSWAGEN" },
// { "id": 15, "name": "HYUNDAI" },
// { "id": 16, "name": "MERCEDES-BENZ" },
// { "id": 17, "name": "AUDI" },
// { "id": 18, "name": "LEXUS" },
// { "id": 19, "name": "LAND ROVER" },
// { "id": 20, "name": "MITSUBISHI" },
// { "id": 21, "name": "VOLVO" },
// { "id": 22, "name": "JAGUAR" },
// { "id": 23, "name": "PORSCHE" },
// { "id": 24, "name": "MAZDA" },
// { "id": 25, "name": "SUBARU" },
// { "id": 26, "name": "FIAT" },
// { "id": 27, "name": "ALFA ROMEO" },
// { "id": 28, "name": "CITROEN" },
// { "id": 29, "name": "SKODA" },
// { "id": 30, "name": "SEAT" },
// { "id": 31, "name": "DS" },
// { "id": 32, "name": "SMART" },
// { "id": 33, "name": "MASERATI" },
// { "id": 34, "name": "BENTLEY" },
// { "id": 35, "name": "ASTON MARTIN" },
// { "id": 36, "name": "ROLLS-ROYCE" },
// { "id": 37, "name": "LAMBORGHINI" },
// { "id": 38, "name": "FERRARI" },
// { "id": 39, "name": "BUGATTI" },
// { "id": 40, "name": "MCLAREN" },
// { "id": 41, "name": "LOTUS"}
